### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by if6was9** [algesten/jsondiff#16]
You have a great tool here.  It would be great if it was published into maven central.

I'm doing  source copy into our source tree build for the time being, but would love to change this so that this could be pulled form maven central.

Willing to help.

**Comment by anthonydahanne** [comment]
Hello, 
I volunteer to push to Maven central.
According to the official doc at http://central.sonatype.org/pages/ossrh-guide.html#releasing-to-central , someone with a Jira account coudl create a ticket to ask for rights to push artifacts with com.github.foodev groupid.
I'd be happy to push 2.0.0 to central with my existing sonatype creds.
Thanks

**Comment by algesten** [comment]
Hey @anthonydahanne. Please do what you want with this project. I left java development altogether. I've made you a collaborator, or I'll happily donate the repo if you want to maintain it.

**Comment by anthonydahanne** [comment]
Hello @algesten , ok I've created an issue in Sonatype OSS Jira, this is the first step to publish to Maven Central.

https://issues.sonatype.org/browse/OSSRH-17108

For now making me a collaborator of the repo, like you just did, is enough I suppose.
thank you

**Comment by anthonydahanne** [comment]
Hello @algesten again !
I have created a new PR for releasing to central , PR #24 
Could you please merge those 2 PRs #24  and #23 ?
Or do you know someone who would ? Merging my own PRs sound ... not that good...
Unless you tell me you're ok with it
thanks again !

**Comment by algesten** [comment]
@anthonydahanne Merge it yourself. You do whatever you want ;)

**Comment by anthonydahanne** [comment]
Pushed to maven central ! 
https://github.com/algesten/jsondiff/releases
